#ifndef FUNCTION_GEN_H
#define FUNCTION_GEN_H

#include <stdint.h>

// Handles waveform mode
typedef enum {
    WAVE_SINE,
    WAVE_SAW,
    WAVE_TRI,
    WAVE_SQUARE
} waveform_t;

extern volatile waveform_t waveform_mode;
extern volatile uint32_t phase_acc;
extern volatile uint32_t phase_step;

// Convert 32-bit phase accumulator to a table index
// tbl_size must be a power of two (e.g. 256, 1024, 4096)
#define PHASE_TO_INDEX(acc, tbl_size) ((acc) >> (32 - __builtin_ctz(tbl_size)))


// This is the timer that will handle the function generator calculations
// The interrupt generated by this timer is essentially a metronome
void timer0a_init(void);

#endif