#ifndef FUNCTION_GEN_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "config.h"

#define FUNCTION_GEN_H
#define WAVE_BUF_LEN 240
#define PG1 (1<<1)
#define PK4 (1<<4)

// Handles waveform mode
typedef enum {
    WAVE_SINE,
    WAVE_SAW,
    WAVE_TRI,
    WAVE_SQUARE
} waveform_t;

// Used for generating next sample
extern volatile waveform_t waveform_mode;
extern volatile uint32_t phase_acc;
extern volatile uint32_t phase_step;
extern volatile uint16_t current_sample;
extern volatile int current_channel; // 0 = Left, 1 = Right
uint16_t next_sample(void);

// Used for DMA to send sample to SSI3 for I2S DAC output
void fillPingBuffer(uint16_t *buffer, size_t frameCount);
void fillPongBuffer(uint16_t *buffer, size_t frameCount);

// Used for displaying mono 
uint16_t display_buffer[SCOPE_BUFFER_SIZE];
extern volatile size_t scope_write_index;

void draw();

// Convert 32-bit phase accumulator to a table index
// tbl_size must be a power of two (e.g. 256, 1024, 4096)
// EXAMPLE: 
// the sine table is 256 points ( see waveform.h )
// only need 256 = 2^8, therefore only need 8 bits of the phase accumulator to walk thru the table.
// phase_acci s a 32 bit int, therefore, extract the top 8 bits by shifting right. 32 - 8 = 24.
#define PHASE_TO_INDEX(acc, tbl_size) ((acc) >> (32 - __builtin_ctz(tbl_size)))

// This is the timer that will handle the function generator calculations
// The interrupt generated by this timer is essentially a metronome
void init_timer0a(void);
void init_PG1(void);  // for testing
void init_PK4(); // for testing
#endif